### ISSUE TITLE
Figure out 100% bug

### ISSUE THREAD

**Issue by Kimundi** [Diggsey/ruplace#15]
It seems that sometimes the tool reports something like `1544/1545 (99.9%)` followed by a "Nothing to be done (for now)".

This is either a off-by-one bug, or a race condition with other pixel placers, but ideally we should only detect 100% as a nothing-to-be-done scenario.

**Comment by Diggsey** [comment]
I already fixed this, but it's not released, it was an off-by-one bug 😛
